version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
  nodejs:
    build: ./nodejs
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=myPassword@Rader
      - DB_NAME=app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=myPassword@Rader
      - MYSQL_DATABASE=app
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
